
export const PARLIMEN_DUN: Record<string, string[]> = {
  "P44 PERMATANG PAUH": ["N10 SEBERANG JAYA", "N11 PERMATANG PASIR", "N12 PENANTI"],
  "P45 BUKIT MERTAJAM": ["N13 BERAPIT", "N14 MACHANG BUBUK", "N15 PADANG LALANG"],
  "P46 BATU KAWAN": ["N16 PERAI", "N17 BUKIT TENGAH", "N18 BUKIT TAMBUN"]
};

export const JAWATAN_AJK = [
  "PENGERUSI", 
  "TIMBALAN PENGERUSI", 
  "SETIAUSAHA", 
  "BENDAHARI", 
  "AJK", 
  "AJK WANITA", 
  "PEMERIKSA KIRA-KIRA"
];

export const JAWATAN_PEGAWAI = ["IMAM", "BILAL", "SIAK"];

export const POSITION_RANK: Record<string, number> = {
  "PENGERUSI": 1,
  "TIMBALAN PENGERUSI": 2,
  "SETIAUSAHA": 3,
  "BENDAHARI": 4,
  "AJK": 5,
  "AJK WANITA": 6,
  "PEMERIKSA KIRA-KIRA": 7,
  "IMAM": 8,
  "BILAL": 9,
  "SIAK": 10
};
