
export const PARLIMEN_DUN: Record<string, string[]> = {
  "P41 KEPALA BATAS": ["N01 PENAGA", "N02 BERTAM", "N03 PINANG TUNGGAL"],
  "P42 TASEK GELUGOR": ["N04 PERMATANG BERANGAN", "N05 SUNGAI DUA", "N06 TELOK AYER TAWAR"],
  "P43 BAGAN": ["N07 SUNGAI PUYU", "N08 BAGAN JERMAL", "N09 BAGAN DALAM"],
  "P44 PERMATANG PAUH": ["N10 SEBERANG JAYA", "N11 PERMATANG PASIR", "N12 PENANTI"],
  "P45 BUKIT MERTAJAM": ["N13 BERAPIT", "N14 MACHANG BUBUK", "N15 PADANG LALANG"],
  "P46 BATU KAWAN": ["N16 PERAI", "N17 BUKIT TENGAH", "N18 BUKIT TAMBUN"],
  "P47 NIBONG TEBAL": ["N19 JAWI", "N20 SUNGAI BAKAP", "N21 SUNGAI ACHEH"],
  "P48 BUKIT BENDERA": ["N22 TANJONG BUNGA", "N23 AIR PUTIH", "N24 KEBUN BUNGA", "N25 PULAU TIKUS"],
  "P49 TANJONG": ["N26 PADANG KOTA", "N27 PENGKALAN KOTA", "N28 KOMTAR"],
  "P50 JELUTONG": ["N29 DATOK KERAMAT", "N30 SUNGAI PINANG", "N31 BATU LANCANG"],
  "P51 BUKIT GELUGOR": ["N32 SERI DELIMA", "N33 AIR ITAM", "N34 PAYA TERUBONG"],
  "P52 BAYAN BARU": ["N35 BATU UBAN", "N36 PANTAI JEREJAK", "N37 BATU MAUNG"],
  "P53 BALIK PULAU": ["N38 BAYAN LEPAS", "N39 PULAU BETONG", "N40 TELOK BAHANG"]
};

export const JAWATAN_AJK = [
  "PENGERUSI", 
  "TIMBALAN PENGERUSI", 
  "SETIAUSAHA", 
  "BENDAHARI", 
  "AJK", 
  "AJK WANITA", 
  "PEMERIKSA KIRA-KIRA 1",
  "PEMERIKSA KIRA-KIRA 2"
];

export const JAWATAN_PEGAWAI = ["IMAM", "BILAL", "SIAK"];

export const POSITION_RANK: Record<string, number> = {
  "PENGERUSI": 1,
  "TIMBALAN PENGERUSI": 2,
  "TIMB. PENGERUSI": 2,
  "TIMB PENGERUSI": 2,
  "SETIAUSAHA": 3,
  "BENDAHARI": 4,
  "AJK": 5,
  "AHLI JAWATANKUASA": 5,
  "AJK WANITA": 6,
  "PEMERIKSA KIRA-KIRA 1": 7,
  "PEMERIKSA KIRA-KIRA 2": 8,
  "PEMERIKSA KIRA-KIRA": 7,
  "IMAM": 9,
  "BILAL": 10,
  "SIAK": 11
};

export const SENARAI_MASJID_STATIC = [
  "MASJID ALMA JAYA", "MASJID BAGAN NYIOR JURU", "MASJID BALIK BUKIT", "MASJID BATU KG PERTAMA", "MASJID BUKIT INDERA MUDA", "MASJID BUKIT TEH", "MASJID CHEROK TOK’KUN BAWAH", "MASJID GUAR PERAHU", "MASJID HAJI MD DESA", "MASJID HAJI SAAD TANAH LIAT", "MASJID JALAN BAHARU PERAI", "MASJID KG PELET", "MASJID KG SEKOLAH JURU", "MASJID KG SETOL", "MASJID KEBUN SIREH", "MASJID KG ALMA", "MASJID KG BARU ALMA", "MASJID KUALA JURU", "MASJID KUALA MENGKUANG", "MASJID KUALA TASEK", "MASJID KUBANG SEMANG", "MASJID KUBANG ULU", "MASJID MACHANG BUBUK", "MASJID MENGKUANG SEMARAK", "MASJID MENGKUANG TITI", "MASJID PADANG IBU", "MASJID PADANG LALANG", "MASJID PAPAN KG PERTAMA", "MASJID PENGKALAN TAMBANG", "MASJID PERAI", "MASJID PERMATANG BATU", "MASJID PERMATANG JANGGUS", "MASJID PERMATANG NIBONG", "MASJID PERMATANG PASIR", "MASJID PERMATANG PAUH", "MASJID PERMATANG TINGGI", "MASJID SAMA GAGAH", "MASJID SEBERANG JAYA", "MASJID SEMBILANG", "MASJID SUNGAI RAMBAI", "MASJID TAMAN GUAR PERAHU", "MASJID TAMAN PELANGI", "MASJID TASEK JUNJONG", "MASJID TENGAH BERAPIT", "MASJID TIMAH", "MASJID TOK LEBAI HASHIM", "MASJID TOKUN ATAS", "MASJID TUAN ABDULLAH", "MASJID DAERAH SEBERANG PERAI TENGAH", "MASJID AL-MUSTAQIM"
];
